server {
    listen       80;
    server_name  localhost;

    charset utf-8;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # Make React Router client-side routing work by falling back to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optionally cache static assets for performance
    location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff2?|eot|ttf|otf|mp4|webm|wav|mp3|m4a|aac|oga)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public";
        try_files $uri =404;
    }
}
